---
# tasks file for create_Domain
- name: Install IIS (Web-Server only)
  ansible.windows.win_feature:
    name: Web-Server
    state: present
    include_management_tools: yes

- name: Create directory structure
  ansible.windows.win_file:
    path: C:\Windows\NTDS
    state: directory
  become_method: runas

- name: Install DNS server role
  ansible.windows.win_feature:
    name: DNS
    state: present
    include_sub_features: yes
    include_management_tools: yes

- name: Create Active Directory Domain
  ansible.windows.win_domain:
    dns_domain_name: cyber.com
    safe_mode_password: lHVqnFqJi5XCQ@A$
  register: domain_result

- name: Reboot the server if necessary
  ansible.windows.win_reboot:
  when: domain_result.reboot_required

- name: Set up the domain controller on windows server 
  ansible.windows.win_domain_controller:
    dns_domain_name: cyber.com
    state: domain_controller
    domain_admin_user: adminuser@cyber.com
    domain_admin_password: lHVqnFqJi5XCQ@A$
    safe_mode_password: lHVqnFqJi5XCQ@A$
    database_path: C:\Windows\NTDS
    sysvol_path: C:\Windows\SYSVOL
    install_dns: yes