---
# tasks file for copy_files
- name: Example from an Ansible Playbook 
  win_ping:
    

- name: copy file to windows
  ansible.windows.win_file:
    hosts: win 
    path: "C:/Users/adminuser/Desktop/ansible files/file.txt"
    state: touch